### ISSUE TITLE
Create Tracking Script

### ISSUE THREAD

**Issue by Bojak4616** [Bojak4616/Mobile_Phone_Tracking#12]
Main contribution:
if vMAC broadcast probe req -> probe respond with any SSID-> get rMAC -> confirm desired rMAC -> save vMAC tags from initial probe req -> listen to all vMACs with same tags -> start responding to vMACs with confirmed tags in order to track target.

**Comment by ndcg91** [comment]
I know that it is very old and it is a closed issue. But just a question. 
Responding to the probe requests of the devices ensure that futher probe request are sent and a the sequence number become more predictable?
I am trying to implement something like this to count number of concurrent devices. My main issue now is that secuence numbers cannot be entirelly trusted.
