### ISSUE TITLE
Website purpose

### ISSUE THREAD

**Issue by Bojak4616** [Bojak4616/Mobile_Phone_Tracking#13]
@csanders-git What do you think about changing the website to have functionality that lets a user input a MAC address, which gets sent to a listening device that will serve up the attack. It will then respond back to the website with a yes/no and some other info about if the MAC is near the device or not. 

Presumably it would keep looking for/tracking the MAC until the user requests it to stop.

**Comment by SecurityDozo** [comment]
This will instead be in the form of a blog post.

Will implement at a later date.
