### ISSUE TITLE
Device fingerprinting techniques

### ISSUE THREAD

**Issue by Bojak4616** [Bojak4616/Mobile_Phone_Tracking#2]
Use examples from the paper, in earlier sections, to be able to fingerprint devices. Since I'll only really be working with my Nexus 6p, I should be able to pick it out quickly.

**Comment by SecurityDozo** [comment]
Best way to do this is to setup a "unique" SSID that the phone will send probes out to look for. this way I can see the SSID and identify my device even if the MAC changes

**Comment by SecurityDozo** [comment]
Fields that should be remembered in vMAC: Supported Rates, High Throughput capabilities and Interworking Capabilities. In addition to those tags and their values, the order in which the tags appear should be remembered. 

This fingerprinting technique is pointed out in Section 3.1 of the attached paper.
[asiaccs2016.pdf](https://github.com/Bojak4616/Mobile_MAC_DeRandomization/files/931648/asiaccs2016.pdf)
