### ISSUE TITLE
Investigate the need for a script to obtain SSID/BSSID/ESSID

### ISSUE THREAD

**Issue by Bojak4616** [Bojak4616/Mobile_Phone_Tracking#3]
This can be done with the aircrack suite. However, it would be nice to have everything in python functions so that they can be called to quickly grab what is in the air. The benefit to this approach is the ability to grab and use the SSID/BSSID/ESSID's quickly and interchangeably. 

This would be good for larger scale operations. Since I only have one device available, maybe not.

I'm leaning yes since it's not much work. Have to look into a tad more.

**Comment by SecurityDozo** [comment]
Going forward with this. Nice intro to wireless scapy

**Comment by SecurityDozo** [comment]
Because of time constraints, this will not be implemented.
