### ISSUE TITLE
Deauthentication Script

### ISSUE THREAD

**Issue by Bojak4616** [Bojak4616/Mobile_Phone_Tracking#4]
This should be pretty easy. Follow this guide without copying the code too much. Reference cite anyway because he is a cool dude.

http://raidersec.blogspot.com/2013/01/wireless-deauth-attack-using-aireplay.html

**Comment by SecurityDozo** [comment]
Added in commit 37e4727d0a96683a1d6cee670cff382ceb3e08c6
