### ISSUE TITLE
Clarify requirements for Sequence Number attack

### ISSUE THREAD

**Issue by Bojak4616** [Bojak4616/Mobile_Phone_Tracking#8]
According to the paper, additional information needs to be correlated to get to the global MAC.

Paper also implies that you don't need the global MAC as you can follow the generated sequence numbers and connect them to the local MAC. However, this is not as good as getting to the global MAC.

**Comment by SecurityDozo** [comment]
It was determined that sequence numbers aren't a good factor when trying to track changing vMACs. In the event that a packet is lost or missed, the chain of association is broken.
